// Cube-sphere quadtree terrain. Design Â§6.8.
//
// Six root faces, recursively subdivided against a screen-space error metric
// relative to camera altitude. Crack prevention by edge-index stitching, not
// skirts. Collision cooked only near the player, async, off the game thread.
//
// **Geometry is generated on worker threads.** ADR-0002 measured a 33x33 patch
// at 5â€“8 ms of game-thread time and concluded that was the ceiling on the whole
// implementation â€” the budget could buy smooth frames or a filled horizon, not
// both. Moving generation to the task graph removes the choice: the game thread
// now only uploads finished vertex buffers, and the machine's other cores do the
// sampling. That is also what makes a real-scale planet and a seven-octave
// ridged multifractal affordable at all.
//
// Nanite is deliberately absent: its clusters are built offline, so a
// runtime-generated streamed quadtree cannot use it (design Â§6.8, amended v1.1).

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "LedgerPatchCache.h"
#include "LedgerQuadNode.h"
#include "LedgerTerrainMath.h"
#include "LedgerPatchComponents.h"
#include "ProceduralMeshComponent.h"
#include <atomic>
#include "LedgerPlanet.generated.h"

class UMaterialInterface;
class UProceduralMeshComponent;

/// One patch of geometry being generated on a worker thread.
///
/// Every input is copied in at launch so the worker never touches the actor, the
/// quadtree, or anything else the game thread may be mutating. That is the whole
/// thread-safety argument, and it is why the inputs are values rather than
/// pointers.
struct FLedgerPatchJob
{
	// ---- inputs, immutable once launched --------------------------------
	uint64 Key = 0;
	int32 SectionIndex = INDEX_NONE;
	bool bWithCollision = false;

	ELedgerCubeFace Face = ELedgerCubeFace::PositiveX;
	double U = 0.0;
	double V = 0.0;
	double Extent = 1.0;
	FVector3d Centre = FVector3d::ZeroVector;

	FLedgerTerrainParams Params;
	int32 Side = 33;

	/// Approximate world-space extent of the node, centimetres. Baked into the
	/// vertices so the shader can work out how close this patch is to being
	/// collapsed without being told per frame.
	double WorldSize = 0.0;

	/// Edges that border a coarser neighbour and therefore need stitching.
	bool bStitchLeft = false;
	bool bStitchRight = false;
	bool bStitchBottom = false;
	bool bStitchTop = false;

	// ---- outputs --------------------------------------------------------
	TArray<FVector> Vertices;
	TArray<int32> Triangles;
	TArray<FVector> Normals;
	TArray<FVector2D> UVs;

	/// Geomorph data, one per vertex: X is how far this vertex must move along
	/// its radial to sit where the *parent* LOD would have put it, and Y is the
	/// node's world size.
	///
	/// Only a scalar is needed rather than a full offset, because the coarse
	/// position is taken as the same direction at the interpolated elevation.
	/// The true midpoint of two points on a sphere is slightly inside it, and
	/// that chord-versus-arc error at patch scale is a fraction of a millimetre
	/// — far below the elevation difference this is correcting.
	TArray<FVector2D> MorphUVs;
	TArray<FColor> Colors;
	TArray<FProcMeshTangent> Tangents;

	/// The sea surface for this patch, as a second mesh section.
	///
	/// Water rides the terrain quadtree rather than having a quadtree of its
	/// own: it inherits the LOD, it is generated by the same job on the same
	/// thread, and its resolution can never disagree with the coastline it meets.
	/// A separate water tree would be a second streaming system to keep in step
	/// with the first, and the seam between them would be exactly at the
	/// shoreline, where it is most visible.
	TArray<FVector> WaterVertices;
	TArray<int32> WaterTriangles;
	TArray<FVector> WaterNormals;
	TArray<FVector2D> WaterUVs;
	TArray<FColor> WaterColors;
	TArray<FProcMeshTangent> WaterTangents;
	bool bHasWater = false;

	double GenerationMs = 0.0;

	/// Written last by the worker, read by the game thread. Release/acquire, so
	/// the buffers above are guaranteed visible once this reads true.
	std::atomic<bool> bComplete{false};

	/// Set by the game thread when the patch is no longer wanted â€” the LOD moved
	/// on while it was in flight. The result is dropped rather than uploaded.
	std::atomic<bool> bAbandoned{false};
};

using FLedgerPatchJobRef = TSharedPtr<FLedgerPatchJob, ESPMode::ThreadSafe>;

/// What a live section was built from, so that releasing it can be undone.
///
/// The stitch flags cannot be recovered from the mesh and cannot be recomputed
/// at release either â€” a collapse destroys the node before its section goes
/// back to the pool. They are recorded on the way in.
struct FLedgerSectionMeta
{
	uint64 Key = 0;
	FVector3d Centre = FVector3d::ZeroVector;
	bool bStitchLeft = false;
	bool bStitchRight = false;
	bool bStitchBottom = false;
	bool bStitchTop = false;
};

/// What the terrain is doing, for the Â§15.1 build/buy decision.
USTRUCT()
struct FLedgerTerrainStats
{
	GENERATED_BODY()

	UPROPERTY()
	int32 VisibleNodes = 0;

	UPROPERTY()
	int32 NodesWithCollision = 0;

	UPROPERTY()
	int32 JobsInFlight = 0;

	UPROPERTY()
	int32 PendingBuilds = 0;

	UPROPERTY()
	int64 TotalBuilds = 0;

	UPROPERTY()
	int32 DeepestVisibleDepth = 0;

	/// Game-thread milliseconds spent uploading finished patches last frame.
	///
	/// This used to say upload was "the only terrain cost on the game thread".
	/// It was not, and nothing had checked: the LOD walk cost three times as
	/// much. See WorstTreeMs below and docs/comparisons/terrain-component.md.
	UPROPERTY()
	double LastFrameUploadMs = 0.0;

	UPROPERTY()
	double WorstFrameUploadMs = 0.0;

	/// Worker-thread milliseconds for a single patch. Off the critical path, so
	/// this can be large without costing a frame â€” it only bounds throughput.
	UPROPERTY()
	double LastPatchGenerationMs = 0.0;

	UPROPERTY()
	double WorstFrameCollisionMs = 0.0;

	/// Visible leaves with no geometry and no ancestor covering for them. This
	/// is the count of actual holes in the planet, as distinct from leaves
	/// merely waiting on a finer LOD â€” a split parent keeps its geometry until
	/// all four children have theirs, so waiting normally costs detail, not a
	/// hole. Anything but zero here is a hole somebody can fly through.
	UPROPERTY()
	int32 UnfilledNodes = 0;

	UPROPERTY()
	int32 WorstUnfilled = 0;

	/// When the worst happened. A peak with no timestamp cannot be attributed,
	/// and the difference between a climb and a teleport is the whole question.
	UPROPERTY()
	double WorstUnfilledAt = 0.0;

	/// Section pool accounting. A starved frame is either too much demand or a
	/// pool that is not being returned to, and the two have nothing in common.
	UPROPERTY()
	int32 SectionsActive = 0;

	UPROPERTY()
	int32 SectionsFree = 0;

	UPROPERTY()
	int32 SectionsPending = 0;

	/// Where the terrain tick's game-thread time goes, in milliseconds, worst
	/// frame so far.
	///
	/// LastFrameUploadMs above says upload "is now the *only* terrain cost on
	/// the game thread". Nobody measured that. The game thread has been over
	/// budget for the whole project -- 20 to 33 ms at low altitude against
	/// 16.7, with the GPU idle at 5 to 9 -- and upload worsts at about 5, so
	/// something else is spending the rest of it.
	UPROPERTY()
	double WorstTreeMs = 0.0;

	UPROPERTY()
	double WorstHarvestMs = 0.0;

	UPROPERTY()
	double WorstCollectMs = 0.0;

	UPROPERTY()
	double WorstSortMs = 0.0;

	UPROPERTY()
	double WorstImbalanceMs = 0.0;

	UPROPERTY()
	double WorstTickMs = 0.0;

	/// The whole terrain tick, this frame. Worsts say how bad it ever got;
	/// this is what the flight recorder samples so the cost can be reported
	/// against the phase of flight it happened in, which is the only form in
	/// which it answers anything -- the game thread is fine in orbit and 20 ms
	/// over on approach, and one number for the run averages those together.
	UPROPERTY()
	double LastTickMs = 0.0;

	/// Adjacent visible leaves whose depths differ by more than one.
	///
	/// Edge stitching collapses a finer node's odd edge vertices onto their even
	/// neighbours, which closes a one-level difference exactly. It cannot close
	/// two: the finer node would have to collapse two levels of vertices and it
	/// only knows how to collapse one. Any count here is a crack somewhere.
	UPROPERTY()
	int32 ImbalancedEdges = 0;

	UPROPERTY()
	int32 WorstDepthDifference = 0;

	UPROPERTY()
	int32 WaterSections = 0;

	/// Patches served from the cache against patches that had to be generated.
	/// The ratio of these two is the whole argument for the cache existing.
	UPROPERTY()
	int64 CacheHits = 0;

	UPROPERTY()
	int64 CacheMisses = 0;

	UPROPERTY()
	int64 CacheEvictions = 0;

	UPROPERTY()
	int32 CacheEntries = 0;

	UPROPERTY()
	double CacheMegabytes = 0.0;
};

UCLASS()
class LEDGERTERRAIN_API ALedgerPlanet : public AActor
{
	GENERATED_BODY()

public:
	ALedgerPlanet();

	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type Reason) override;
	virtual void Tick(float DeltaSeconds) override;

	/// Reference sphere radius in centimetres. Earth: 6,371 km.
	///
	/// LWC carries this without complaint â€” 6.37e8 cm is well inside a double's
	/// envelope (Â§6.8) â€” and the mesh does not care either, because vertices are
	/// built relative to each node's own centre and never leave float range.
	UPROPERTY(EditAnywhere, Category = "Ledger|Planet")
	double Radius = 637100000.0;

	/// Peak elevation above the reference sphere. Earth's is about 9 km, which
	/// is 0.14% of its radius â€” invisible from orbit, and correctly so. What
	/// makes a planet read from space is the coastline, not the relief.
	UPROPERTY(EditAnywhere, Category = "Ledger|Planet")
	double MaxElevation = 900000.0;

	/// Where the waterline sits in the continent noise, in [-1, 1]. Higher means
	/// less land; Earth is about 71% ocean.
	/// 0.14 puts roughly two thirds of the surface under water, which is close
	/// to Earth and, more to the point, gives coastlines something to be a coast
	/// *of*. At 0.06 the planet was one supercontinent with ponds.
	UPROPERTY(EditAnywhere, Category = "Ledger|Planet")
	double SeaLevel = 0.14;

	UPROPERTY(EditAnywhere, Category = "Ledger|Planet")
	int32 Seed = 20260908;

	/// Vertices along one edge of a node's grid. Must be odd so edge stitching
	/// has a midpoint to collapse.
	/// 65 rather than 33: a patch with twice the vertices per side covers four
	/// times the ground at the same screen-space error, so the same triangle
	/// count arrives in a quarter of the draw calls. At 33 the visible set hit
	/// eighteen thousand components and the pool starved into a checkerboard of
	/// holes.
	UPROPERTY(EditAnywhere, Category = "Ledger|Planet")
	int32 GridResolution = 65;

	/// 15 levels of 64-quad patches over a 6,371 km planet: ~4.8 m quads.
	UPROPERTY(EditAnywhere, Category = "Ledger|Planet")
	int32 MaxDepth = 15;

	/// Subdivide when a node's projected error exceeds this many pixels.
	/// Paired with the patch resolution above: together they set how many
	/// components the visible set needs. 150 px with 65-vertex patches lands
	/// near a thousand, which the pool can actually serve.
	UPROPERTY(EditAnywhere, Category = "Ledger|LOD")
	double ErrorThresholdPixels = 150.0;

	/// Patches allowed in flight at once. Bounded so a fast turn cannot queue
	/// thousands of jobs whose results are stale before they land.
	UPROPERTY(EditAnywhere, Category = "Ledger|LOD")
	int32 MaxJobsInFlight = 128;

	/// Milliseconds per frame the game thread may spend uploading finished
	/// patches. Generation is no longer on this budget â€” only the upload is.
	UPROPERTY(EditAnywhere, Category = "Ledger|LOD")
	double UploadBudgetMs = 6.0;

	/// Cook collision within this distance of the camera.
	UPROPERTY(EditAnywhere, Category = "Ledger|Collision")
	double CollisionRadius = 300000.0;

	/// Cook ahead along the velocity vector by this many seconds of travel.
	/// Predictive, never on demand â€” Â§6.8's one non-negotiable.
	UPROPERTY(EditAnywhere, Category = "Ledger|Collision")
	double CollisionLeadSeconds = 2.5;

	/// Subdivide ahead along the velocity vector by this many seconds.
	///
	/// Longer than the collision lead, because geometry is the slower of the
	/// two: a patch has to be queued, sampled on a worker and uploaded, where a
	/// cook only has to happen. Arriving somewhere that was decided a moment
	/// ago means arriving before the decision has finished being acted on.
	UPROPERTY(EditAnywhere, Category = "Ledger|LOD")
	double GeometryLeadSeconds = 3.0;

	/// Memory the patch cache may hold, in megabytes.
	///
	/// Bounded by bytes rather than by entries because entries are not the same
	/// size: a patch over open water carries a second mesh section and a patch
	/// inland does not. A count would be a budget for the average patch and a
	/// surprise for every other one.
	///
	/// A 65-vertex patch is around 700 KB of interleaved vertices, so this holds
	/// roughly seven hundred of them â€” a few minutes of flying, which is the
	/// span over which a player actually retraces ground.
	UPROPERTY(EditAnywhere, Category = "Ledger|LOD")
	double PatchCacheBudgetMB = 512.0;

	const FLedgerTerrainStats& GetStats() const { return Stats; }

	/// Height of the surface above the reference sphere at a direction.
	double SurfaceRadiusAt(const FVector3d& UnitDirection) const;

	FLedgerTerrainParams TerrainParams() const;

	/// Set before BeginPlay by whoever spawns the planet. The quadtree's
	/// business is geometry; what it is painted with is not its decision.
	void SetMaterials(UMaterialInterface* Surface, UMaterialInterface* Water)
	{
		SurfaceMaterial = Surface;
		WaterMaterial = Water;
	}

private:
	UPROPERTY()
	TObjectPtr<USceneComponent> Root;

	/// The pool, in whichever component type this run is measuring. Held as
	/// the base type so the two candidates share every line of the streaming
	/// code except the upload itself; see LedgerPatchComponents.h.
	UPROPERTY()
	TArray<TObjectPtr<UMeshComponent>> MeshPool;

	ELedgerPatchComponent ComponentKind = ELedgerPatchComponent::Procedural;

	/// The pooled component as a procedural one, or null when this run is
	/// measuring the other backend. The patch cache stores FProcMeshSection
	/// and therefore only exists for the procedural path -- which is one of
	/// the differences being measured, not an oversight.
	UProceduralMeshComponent* PooledProcedural(int32 SectionIndex) const;

	UPROPERTY()
	TObjectPtr<UMaterialInterface> SurfaceMaterial;

	/// The surface material with the geomorph parameters bound.
	///
	/// One instance for the whole planet rather than one per patch: the two
	/// things the blend needs that change — where the camera is and how wide
	/// the viewport is — are the same for every patch in a frame, and the one
	/// thing that differs per patch is baked into its vertices.
	UPROPERTY()
	TObjectPtr<UMaterialInstanceDynamic> SurfaceInstance;

	UPROPERTY()
	TObjectPtr<UMaterialInterface> WaterMaterial;

	TArray<TUniquePtr<FLedgerQuadNode>> Roots;

	/// Leaf key -> index into `MeshPool`, for patches whose geometry is live.
	TMap<uint64, int32> ActiveSections;
	/// Leaf key -> job, for patches currently being generated.
	TMap<uint64, FLedgerPatchJobRef> InFlight;

	/// Per-section record of what is loaded there, parallel to `MeshPool`.
	TArray<FLedgerSectionMeta> SectionMeta;

	/// Geometry for patches that were drawn and are not drawn now. Nothing in
	/// here is on screen; entries exist so that wanting a patch again costs an
	/// upload rather than a generation.
	FLedgerPatchCache PatchCache;
	TArray<int32> FreeSections;

	FLedgerTerrainStats Stats;
	TArray<IConsoleObject*> ConsoleCommands;

	FVector3d LastCameraLocal = FVector3d::ZeroVector;
	FVector3d CameraVelocityLocal = FVector3d::ZeroVector;
	double NextTraceAt = 0.0;

	void BuildRoots();
	void UpdateTree(FLedgerQuadNode& Node, const FVector3d& CameraLocal, const FVector3d& LeadLocal, double ViewportWidth, double FovRadians, bool bForceCollapse);
	void CollectLeaves(const FLedgerQuadNode& Node, TArray<const FLedgerQuadNode*>& Out, bool bAncestorHasGeometry) const;
	void Split(FLedgerQuadNode& Node);
	void Collapse(FLedgerQuadNode& Node);
	bool IsBeyondHorizon(const FLedgerQuadNode& Node, const FVector3d& CameraLocal) const;

	/// Depth of the leaf containing a direction. Used for edge stitching, and it
	/// crosses cube faces for free because it starts from the direction rather
	/// than from a face-local coordinate.
	int32 LeafDepthAt(const FVector3d& UnitDirection) const;

	/// Launches generation on a worker thread. Returns false if the pool or the
	/// in-flight cap is exhausted.
	bool LaunchPatch(const FLedgerQuadNode& Node, bool bWithCollision);

	/// Uploads whatever finished since last frame, within the budget.
	void HarvestCompletedPatches();

	/// Serves a leaf from the cache if the geometry is there and still correct.
	bool UploadFromCache(const FLedgerQuadNode& Node, bool bWithCollision);


	/// The instance if there is one, the base material otherwise. Patches take
	/// this rather than SurfaceMaterial, because the geomorph parameters live on
	/// the instance and a patch wearing the base material would not blend.
	UMaterialInterface* TerrainMaterial() const;

	/// Feeds the geomorph blend the same numbers the LOD decision uses. Called
	/// once a frame; if the two ever disagree the pop does not disappear, it
	/// moves somewhere else.
	void UpdateMorphParameters(double ViewportWidth, double FovRadians);

	void ReleaseSection(uint64 Key);
	void AbandonJob(uint64 Key);

	FVector3d UnitSphereAt(const FLedgerQuadNode& Node, double LocalU, double LocalV) const;

	void LogStats() const;
};

/// Generates a patch's geometry. Free function, no engine state, safe to call
/// from any thread â€” which is the point.
LEDGERTERRAIN_API void LedgerGeneratePatch(FLedgerPatchJob& Job);
