# -*- coding: utf-8 -*-
"""Supplementary tasks: the work that is real but rarely gets planned.

Tooling, CI, UI, audio, input, performance and release. Every one of these is a
thing that has to happen and that a roadmap written only from the design
document would omit, because the design document is about the game rather than
about shipping it.

These are appended to their milestones after the primary tasks, so the linear
order still reads as one narrative per milestone.
"""

from roadmap_data import task

SUPPLEMENT = {
    "M1": [
        task("GitHub Actions: sim suite on every commit",
             "Design SS9 says the sim suite runs on every commit and UE builds nightly. Wire it.",
             "A push runs cargo test and fails the check on a red test.", 2, ["SS9", "SS11"]),
        task("GitHub Actions: nightly UE build and automation tests",
             "Build the editor target and run the Tier 6 suite headless on a schedule.",
             "A nightly run produces a build artifact and a test report.", 3, ["SS9", "SS11"]),
        task("Nightly Tier 3 fuzz job",
             "The 1,000,000 tick invariant run, nightly, with failure notification.",
             "A deliberately broken invariant is caught by the next nightly run.", 2, ["SS11"]),
        task("Terrain debug visualisation modes",
             "Wireframe, LOD level as colour, patch age, collision coverage.",
             "Ledger.Terrain.Debug cycles the modes and each is legible.", 2),
        task("Frame-time HUD and stat capture",
             "A permanent overlay recording frame time, patch queue and memory.",
             "Any capture can be correlated with the frame cost at that moment.", 2, ["SS12"]),
        task("Crash reporting and symbol retention",
             "Keep PDBs per build so a crash from a week-old build is still readable.",
             "A stack from an archived build resolves to source lines.", 2),
    ],
    "M2": [
        task("Screenshot regression harness",
             "Capture fixed viewpoints each nightly build and diff against a baseline.",
             "A material change that alters the look is flagged automatically.", 3, ["SS11"]),
        task("Material complexity budget",
             "Shader instruction counts tracked per material, with a ceiling.",
             "Exceeding the ceiling fails the nightly build.", 2),
        task("Texture memory budget and streaming",
             "Know what the surface costs in VRAM, and leave room for the narration model.",
             "Surface textures stay under budget with 4 GB reserved for inference.", 2, ["SS6.4"]),
        task("Colour grading and tone mapping pass",
             "One look, applied consistently, rather than per-scene exposure fiddling.",
             "The same grade reads correctly in orbit, at altitude and on the ground.", 3),
        task("Time of day and a moving sun",
             "The sun currently never moves. Drive it from sim time.",
             "A full day-night cycle runs and the atmosphere responds correctly at dawn.", 4),
        task("Night side: stars, moonlight, and town lights",
             "The dark half of the planet has to be worth flying over.",
             "Town lights are visible from orbit on the night side.", 3),
    ],
    "M3": [
        task("Input remapping and gamepad support",
             "Axis mappings are hard-coded in config. Support rebinding and a controller.",
             "A gamepad flies the ship with no keyboard input.", 3),
        task("Settings menu in C++",
             "Resolution, quality, input, audio. No UMG assets.",
             "Settings persist across a restart.", 3, ["SS9"]),
        task("Pause, save and quit flow",
             "A session boundary that does not lose state.",
             "Quitting and resuming restores the ship and the world clock.", 2),
        task("Ship interior ambient audio",
             "Hull creak under load, air handling, alarm tones on damage.",
             "Damage produces an audible cue before the HUD shows it.", 2),
        task("Accessibility: subtitles, colourblind-safe HUD, motion options",
             "The HUD encodes state in colour alone in places. Fix that.",
             "Every HUD state is distinguishable without colour.", 3),
    ],
    "M4": [
        task("OpenTelemetry instrumentation in the sim",
             "SS9's observability stack, now that there is a service to observe.",
             "Per-region tick cost and propagation depth export as metrics.", 3, ["SS9", "SS12"]),
        task("Grafana dashboards for the SS12 metrics",
             "Every metric in SS12 on one board, with its target band drawn on.",
             "A metric outside its band is visually obvious without reading numbers.", 2, ["SS12"]),
        task("Structured logging with correlation ids",
             "Trace an intent from client to sim to event to consequence.",
             "One id follows a contract acceptance through every log line it causes.", 2),
        task("Deployment scripts for the sim service",
             "SS10's ops/ tree. Run it somewhere that is not a developer laptop.",
             "The sim runs on a remote host and a local client connects to it.", 3, ["SS10"]),
        task("Database migration path from file log to Postgres",
             "ADR-0001 defers this to Phase 1. This is Phase 1.",
             "The same event log replays identically from a file and from Postgres.",
             4, ["ADR-0001", "SS9"]),
    ],
    "M5": [
        task("Tutorial-free onboarding",
             "The first contract has to teach the loop without a tutorial, because the loop is "
             "the game and a tutorial would tell you the answer.",
             "A new player completes a first contract without instructions, in a playtest.", 4),
        task("Playtest harness and session recording",
             "Record inputs and sim state so a playtest can be replayed and analysed.",
             "A recorded session replays deterministically.", 3, ["SS5.3"]),
        task("First external playtest",
             "Five people who have not seen it. Watch, do not explain.",
             "Written notes from five sessions, with the points where players stalled.", 3),
        task("Investigation UI iteration from playtest findings",
             "Fix whatever the playtest showed, not whatever seemed likely beforehand.",
             "The top three stall points from the playtest are addressed and retested.", 4),
    ],
    "M6": [
        task("Model evaluation harness",
             "Compare candidate models on the actual prompts, measuring latency and refusal rate.",
             "Three models compared on the same 200 prompts with a written recommendation.",
             3, ["SS6.4"]),
        task("Dialogue content pipeline",
             "Authored fallbacks need writing, versioning and coverage measurement.",
             "Every dialogue surface has at least three authored fallbacks.", 3, ["SS6.4"]),
        task("Narration failure modes and graceful degradation",
             "Model missing, VRAM exhausted, service crashed. All three must be survivable.",
             "Killing the narration service mid-conversation degrades to authored text.",
             2, ["SS6.4"]),
    ],
    "M7": [
        task("Market UI: charts that do not lie",
             "Price history with the event that caused each move annotatable.",
             "A player can click a price move and see the article about it.", 4, ["SS6.5"]),
        task("Economic tuning harness",
             "Run parameter sweeps headless and report which land inside the SS12 bands.",
             "A sweep of 200 parameter sets reports the viable region.", 3, ["SS12"]),
        task("Economist review of the model",
             "SS6.5's prior-art warning is explicit: EVE employs professional economists.",
             "Written review on file with the failure modes it identifies.", 3, ["SS6.5"]),
    ],
    "M8": [
        task("Character rendering and variation",
             "Crew and NPCs need bodies that differ. Procedural variation over a base mesh.",
             "Twenty NPCs in one scene, visually distinguishable, at no measurable cost.", 4),
        task("Character animation: idle, walk, sit, gesture",
             "Enough that a person standing in a bar reads as a person.",
             "An NPC transitions between states without a pop.", 4),
        task("Crew audio: voice barks from the narration layer",
             "Short lines, generated text, synthesised or authored.",
             "A crew member's bark reflects a belief they actually hold.", 3, ["SS6.4"]),
    ],
    "M9": [
        task("Mission generation tuning harness",
             "Sweep the query parameters and report archetype distribution and tension age.",
             "A sweep reports which parameters keep every archetype under 35%.", 3, ["SS12"]),
        task("Second external playtest, full loop",
             "Six archetypes, live economy, crew. Watch for the oatmeal problem.",
             "Five sessions, with players asked to describe two contracts they did.", 3),
        task("Content pass on contract presentation",
             "The board text has to carry the tension. Written from state, not templated.",
             "No two contracts on the board read as the same sentence with names swapped.",
             3, ["SS6.6"]),
    ],
    "M10": [
        task("Memory profiling at MVP scale",
             "2,000 entities, five regions, and a planet. Know where the memory goes.",
             "A memory report attributing every 10 MB to a subsystem.", 3),
        task("Sim performance optimisation pass",
             "Profile the tick and cut the top three costs.",
             "Per-region full-fidelity tick under 5 ms with 400 entities present.", 4, ["SS12"]),
        task("Save and load a whole world",
             "Snapshot plus log, restored to a bit-identical state.",
             "A save restored on another machine produces the same state fingerprint.",
             3, ["SS5.3"]),
    ],
    "M11": [
        task("Account and identity handling",
             "Who a player is, minimally and safely. No credentials stored by us.",
             "Sign-in works and stores no password or payment data.", 3),
        task("Anti-cheat posture for a sim-authoritative world",
             "The sim owns state, so cheating means lying about intents. Validate them.",
             "A client sending impossible intents is disconnected and logged.", 3, ["SS6.10"]),
        task("Griefing review across every system",
             "Not only rumour injection: contracts, markets, crew, and presence.",
             "A written review naming each surface and its mitigation.", 3, ["SS6.10", "SS15.8"]),
        task("Third external playtest, multiplayer",
             "Sixteen people who do not know each other.",
             "Written notes, plus the belief graph state before and after.", 3),
    ],
    "M12": [
        task("Release build and packaging pipeline",
             "Cook, package, sign and distribute a build people can install.",
             "A tester installs and runs the build with no engine present.", 4),
        task("Telemetry for the pillar tests in the wild",
             "Instrument the four pillars so they can be measured on real sessions.",
             "Each pillar has a metric that can be read off a live population.", 3, ["SS2", "SS12"]),
        task("Phase 3 assessment and funding materials",
             "SS13.5 is explicit that Phase 3 is not achievable solo. Phase 2 exists to be the "
             "thing you raise money or recruit on.",
             "A written assessment with the metrics and recordings that support it.",
             3, ["SS13.4", "SS13.5"]),
    ],
}
