# -*- coding: utf-8 -*-
"""Roadmap content, milestones M8 through M12."""

from roadmap_data import task

# ---------------------------------------------------------------- M8
M8 = [
    task("Crew as first-class simulated entities",
         "Design SS2.1: crew are the losable thing. They hold beliefs, owe favours, and have "
         "their own fears. Not a stat block attached to the player.",
         "A crew member has a full belief set and can be queried like any other entity.",
         4, ["SS2.1"]),
    task("Hiring: finding, negotiating, and the terms",
         "Who is available depends on who has heard of you and what they believe.",
         "A crew member with a bad belief about the player refuses, and says why.",
         4, ["SS2.1", "SS6.1"]),
    task("Crew skills as access rather than numbers",
         "A crew member's value is which obligation classes they unlock, not a damage modifier.",
         "Hiring a port authority contact opens clean landings that were previously unavailable.",
         3, ["SS6.2"]),
    task("Crew loyalty derived from obligations, not a bar",
         "Loyalty is computed from the favour ledger and the belief graph.",
         "grep for a loyalty scalar: zero hits. Loyalty is a query.", 3, ["SS6.1", "SS6.2"]),
    task("Crew can be bought, frightened, or turned",
         "A rival can approach your crew with money, a threat, or information.",
         "A rival successfully turns a crew member, and the player can find out how.",
         4, ["SS2.1"]),
    task("Crew death and its permanence",
         "SS15.4 is open: how permanent, and is there a mitigation the player can buy?",
         "An ADR recording the decision, and the behaviour matching it.", 3, ["SS15.4", "SS8.5"]),
    task("Crew presence in the world",
         "Crew appear aboard the ship and in the town, positioned from sim state.",
         "A crew member the sim says is at the town is standing in the town.", 3),
    task("Crew dialogue driven by their own beliefs",
         "They tell you what they think is true, which is sometimes wrong.",
         "A crew member reports a stale location sincerely.", 3, ["SS6.1", "SS6.4"]),
    task("Crew-initiated missions",
         "NPCs call in favours on the player. SS6.2 says this is not optional content.",
         "A crew member's creditor calls in a favour and it becomes a contract the player must "
         "answer.", 4, ["SS6.2"]),
    task("Crew roster UI",
         "Who you have, what they open, what they are owed and by whom.",
         "The roster shows obligations in both directions, not a loyalty percentage.", 3),
    task("Crew jeopardy in mission resolution",
         "Bringing crew on a job risks them. The risk is legible before committing.",
         "The player can see, before accepting, which crew are exposed and to what.", 3, ["SS2.1"]),
    task("M8 evidence: losing someone",
         "Record a chain of events ending in a crew loss that the player caused and could have "
         "foreseen, and the reconstruction afterwards.",
         "Recording plus the causal chain from the log, uploaded as milestone evidence.",
         2, ["SS2", "SS2.1"]),
]

# ---------------------------------------------------------------- M9
M9 = [
    task("Audit archetype on the shared algorithm",
         "Hidden variable: who is skimming. Resolution verb: expose or blackmail.",
         "Audit uses the identical investigation code path as Bounty, asserted by a test.",
         4, ["SS6.6", "SS6.3"]),
    task("Interception archetype",
         "Hidden variable: route and timing. Resolution: board, destroy or observe.",
         "Interception constrains a search volume over route-time rather than position, using "
         "the same algorithm.", 4, ["SS6.6"]),
    task("Extraction archetype",
         "Hidden variable: holding location. Resolution: retrieve a person or data.",
         "Extraction resolves against a physically present target.", 4, ["SS6.6"]),
    task("Fabrication archetype",
         "No hidden variable: this one injects. Plant a false belief through the same pipeline "
         "the truth uses.",
         "A fabricated belief propagates identically to a true one and carries "
         "Provenance::Fabricated.", 4, ["SS6.6", "SS6.1"]),
    task("Collection archetype",
         "Hidden variable: debtor whereabouts and assets. Resolution: coerce or negotiate.",
         "Collection surfaces the debtor's assets as a second hidden variable.", 4, ["SS6.6"]),
    task("Generalise the search volume beyond regions",
         "The algorithm currently constrains over RegionId. Make the hidden variable generic so "
         "route-time and identity work without a second implementation.",
         "One generic implementation serves all six archetypes; the old one is deleted.",
         5, ["SS6.3", "SS8.4"]),
    task("Archetype distribution metric in CI",
         "SS12's oatmeal detector, asserted rather than observed.",
         "A 10,000 tick run fails CI if any archetype exceeds 35%.", 2, ["SS12", "SS14 R2"]),
    task("Mission variety from simulation state, not templates",
         "Verify the variety comes from the world. Freeze the sim and confirm the generator "
         "produces almost nothing.",
         "With a static world, contract variety collapses; with a live one it does not.",
         3, ["SS6.6"]),
    task("Contract chaining and consequence",
         "Resolving one contract creates the tension the next one queries.",
         "A resolved contract is traceably the cause of a later one.", 3, ["SS6.6"]),
    task("Difficulty from access rather than numbers",
         "A hard job is one you lack the obligation classes for, not one with more hit points.",
         "Two contracts with identical parameters differ in difficulty by the player's ledger.",
         3, ["SS6.2"]),
    task("M9 evidence: six archetypes, one code path",
         "Capture one contract of each type, plus the test asserting the shared path.",
         "Six recordings and the test output uploaded as milestone evidence.", 2, ["SS6.6"]),
]

# ---------------------------------------------------------------- M10
M10 = [
    task("Aggregate region representation",
         "Distant regions tick statistically: aggregate flows, no individual agents.",
         "A region with no observer costs under 0.05 ms per tick.", 5, ["SS6.7"]),
    task("Reification: aggregate to concrete agents",
         "When a player arrives, approximate state instantiates into individuals consistently.",
         "Arriving at a region twice from the same aggregate state produces the same agents.",
         5, ["SS6.7"]),
    task("Dereification: concrete back to aggregate",
         "When they leave, concrete state folds back without losing information.",
         "Property test: aggregate(reify(A)) == A for arbitrary aggregate state.",
         5, ["SS6.7", "SS11"]),
    task("Concurrent arrival determinism",
         "SS15.3 is open: two players entering a statistical region simultaneously. Who triggers "
         "the transform, and is it deterministic?",
         "An ADR, and a test with two simultaneous arrivals producing one consistent result.",
         4, ["SS15.3", "SS8.5"]),
    task("Belief propagation across the LOD boundary",
         "A rumour must cross from aggregate to concrete and back without being lost or doubled.",
         "A belief injected in an aggregate region is present after reification, at the right "
         "confidence.", 4, ["SS6.7", "SS6.1"]),
    task("Per-region tick cost budget and enforcement",
         "SS12: under 5 ms full fidelity. Measure per region and alert.",
         "The metrics dashboard shows per-region cost and flags any region over budget.",
         3, ["SS12"]),
    task("Server cost per region-tick, measured",
         "SS14 R7: simulation cost scales with world size, not player count. Know the number.",
         "Cost per region-tick is reported continuously and tracked over time.", 3, ["SS14 R7"]),
    task("Scale to 2,000 simulated entities across 5 regions",
         "The MVP scale from SS3, running with LOD.",
         "2,000 entities, 5 regions, under 5 ms per full-fidelity region tick.", 4, ["SS3", "SS12"]),
    task("Seam hunting: find the LOD boundary as a player",
         "Fly between regions repeatedly and try to catch the transform.",
         "No observable discontinuity in entity behaviour across 50 crossings.", 3, ["SS6.7"]),
    task("M10 evidence: the reification property test",
         "Capture the property test output over 100,000 arbitrary aggregate states.",
         "Test output uploaded as milestone evidence.", 1, ["SS11"]),
]

# ---------------------------------------------------------------- M11
M11 = [
    task("IP counsel review against SS6.1 and SS6.10",
         "SS7 requires this before Phase 2. The Nemesis patent expires August 2036; our "
         "differentiator is structural, not cosmetic.",
         "Written counsel opinion on file, and any required changes implemented.", 5, ["SS7"]),
    task("Sim-authoritative multiplayer session",
         "One shard, sim owns all world state, clients hold views.",
         "Two clients see the same world state and cannot disagree about it.", 5, ["SS6.10"]),
    task("Target persistence classes",
         "SS15.2 is open. Unique, Regional and Personal, declared on the contract board.",
         "An ADR, and the board declaring the class of every contract up front.",
         4, ["SS6.10", "SS15.2", "SS8.5"]),
    task("Contested targets and intentional races",
         "A Unique target is shared and the race is the point.",
         "Two players hunting one target both see it move, and only one can resolve it.",
         4, ["SS6.10"]),
    task("Fabrication rate limits and traceability",
         "SS6.10: rumour injection is a griefing surface. Rate-limit per source, require "
         "corroboration above a confidence ceiling.",
         "A coordinated injection attempt by four accounts fails to move a target's standing "
         "past the ceiling.", 4, ["SS6.10", "SS15.8"]),
    task("Client-predicted combat with server validation",
         "Standard posture per SS6.10. No custom netcode before MVP.",
         "Combat feels responsive at 120 ms RTT and the server rejects impossible outcomes.",
         5, ["SS6.10"]),
    task("Presence and region handoff",
         "Players entering and leaving regions drive the LOD transform correctly.",
         "Sixteen players spread across five regions with correct fidelity in each.",
         4, ["SS6.7", "SS6.10"]),
    task("Shard topology decision and ADR",
         "SS15.7: one shard or several with separate world state? It decides whether the world "
         "that lives without you is one world or many.",
         "An ADR with the decision and its consequence for the premise.", 3, ["SS15.7", "SS8.5"]),
    task("Sixteen-player soak test",
         "Sixteen clients, one hour, scripted behaviour plus humans.",
         "No desync, no crash, no duplicated target, memory flat.", 4, ["SS6.10"]),
    task("Server cost model at 32 players",
         "Measure what a shard actually costs, so the revenue relationship is known.",
         "Cost per player-hour reported, with the region-tick component separated out.",
         3, ["SS14 R7"]),
    task("M11 evidence: sixteen players, one hour",
         "Record the soak test with the server metrics alongside.",
         "Recording and metrics uploaded as milestone evidence.", 2),
]

# ---------------------------------------------------------------- M12
M12 = [
    task("Pillar P1: the world does not wait for you",
         "Log out for a week of world time. Come back. Find three specific, causally-explicable "
         "changes that had nothing to do with you.",
         "Three changes found and each traced to its cause in the log.", 3, ["SS2"]),
    task("Pillar P2: consequence legible in hindsight",
         "Take any world-state change and reconstruct the four preceding causes from information "
         "available in-game before it happened.",
         "Four causes reconstructed from in-game information only, not from the event log.",
         3, ["SS2"]),
    task("Pillar P3: knowledge is asymmetric",
         "Two players in the same system holding contradictory, sincerely-held, non-buggy "
         "beliefs about the same fact.",
         "Two players demonstrate the contradiction and both can justify their belief.",
         3, ["SS2"]),
    task("Pillar P4: you are a participant, not a protagonist",
         "A player permanently loses something they spent twenty hours building, through a chain "
         "that was their fault and was foreseeable.",
         "The loss happens, and the player can name the decision that caused it.", 3, ["SS2"]),
    task("Full SS12 metrics run at MVP scale",
         "Every metric in the band, on a live build, with real players.",
         "All nine SS12 metrics inside their target ranges over a 24-hour live run.",
         3, ["SS12"]),
    task("Fresh-agent review pass over the whole codebase",
         "SS8.7, capped at two rounds. Fresh context, checking against SS8.1 to SS8.6 and every "
         "invariant in SS6.",
         "Two rounds complete; everything surviving is recorded as a judgement call.",
         5, ["SS8.7"]),
    task("Architecture documentation refresh",
         "Every ADR current, every architecture doc matching the code.",
         "No ADR describes a decision that has since been reversed without a superseding ADR.",
         3, ["SS8.5"]),
    task("MVP gate review and go/no-go",
         "The four pillar tests, the metrics, and an honest assessment of Phase 3 feasibility.",
         "A written gate decision with evidence for each pillar.", 2, ["SS13.3", "SS13.5"]),
    task("M12 evidence: the four pillar tests",
         "Capture each pillar test being passed, with the supporting reconstruction.",
         "Four recordings and their causal chains uploaded as milestone evidence.", 2, ["SS2"]),
]
