# -*- coding: utf-8 -*-
"""Roadmap content, milestones M4 through M12.

Split from `roadmap_data.py` only because one file of five hundred authored
tasks is harder to review than two of two hundred and fifty.
"""

from roadmap_data import task

# ---------------------------------------------------------------- M4
M4 = [
    task("proto/ schema for the wire contract",
         "Design SS10: proto/ is the only place the sim-client contract is defined, and both "
         "sides generate from it. Entities, factions, contracts, beliefs, market state.",
         "Both the Rust sim and the UE client build from the same .proto with no hand-written "
         "duplicate of any message.", 4, ["SS10", "SS9"]),
    task("Rust protobuf codegen in the sim build",
         "prost or equivalent, wired into build.rs so the generated types are never committed.",
         "Deleting the generated directory and rebuilding produces identical types.", 2, ["SS9"]),
    task("UE protobuf integration as a third-party module",
         "The known slog: UE disables exceptions and RTTI, and its check macro collides with "
         "protobuf headers. Budget it explicitly.",
         "The client links protobuf and round-trips a message in an automation test.", 4, ["ADR-0001"]),
    task("Length-prefixed TCP transport",
         "Phase 1 transport per ADR-0001. Framing, reconnect with backoff, and a heartbeat.",
         "Killing the sim and restarting it reconnects within two seconds with no client restart.",
         3, ["ADR-0001"]),
    task("Sim-side gRPC-free server loop",
         "A tick loop that accepts connections, streams state deltas, and applies client intents.",
         "One client connected costs under 0.5 ms per tick of server time.", 4, ["SS5"]),
    task("World state delta encoding",
         "Send what changed, not the world. Per-entity dirty flags folded from the event log.",
         "Steady-state bandwidth under 32 KB/s per client with 2,000 entities simulated.", 4, ["SS5"]),
    task("Client-side world state cache and interpolation",
         "The client holds a view of sim state and interpolates between ticks for presentation.",
         "Entity positions do not jitter at a 10 Hz sim tick and a 60 Hz render.", 3),
    task("Contract board reading live sim state",
         "Replace the snapshot file. The board reflects contracts as they are posted.",
         "A contract posted in the sim appears on the board within one tick round trip.",
         3, ["SS13.2"]),
    task("Player intent messages",
         "Accept a contract, make an inquiry, offer an incentive, redeem a favour. Typed, "
         "validated server-side.",
         "A malformed or impossible intent is rejected with a typed error, never applied.", 3),
    task("Schema versioning and refusal",
         "The client already refuses a future snapshot schema. Extend that to the wire protocol.",
         "A client one version behind refuses to connect and says why.", 2),
    task("Connection state in the UI",
         "Show connected, reconnecting, and stale-state clearly rather than silently lying.",
         "Killing the sim shows a visible degraded state within two seconds.", 2),
    task("Sim as a service: run headless, log, restart",
         "Process supervision, structured logging, and a clean shutdown that flushes the log.",
         "SIGTERM produces a replayable log with no truncated event.", 2, ["SS5.3"]),
    task("Event log persistence to disk",
         "ADR-0001 defers Postgres; this is the file-backed step before it. Append-only, "
         "chunked, with a manifest.",
         "A 1,000,000 tick run writes a log that replays to a bit-identical state.", 4, ["SS5.3"]),
    task("Replay bisector tool",
         "Design SS11 wants this early. Replay to tick N, bisect for the first divergence.",
         "Given a seeded divergence, the bisector finds the exact event in under a minute.",
         3, ["SS11"]),
    task("World inspector tool",
         "A text or web view of live sim state: entities, beliefs, obligations, market.",
         "Any entity's full belief set is inspectable while the sim runs.", 3, ["SS10"]),
    task("Bridge integration tests",
         "Sim and client in one test harness, asserting state agreement after N ticks.",
         "Client and sim agree on every contract and corp balance after 1,000 ticks.", 3, ["SS11"]),
    task("M4 evidence: kill-the-sim recording",
         "Record the client degrading and recovering.",
         "Recording uploaded as milestone evidence.", 1),
]

# ---------------------------------------------------------------- M5
M5 = [
    task("Contract board UI with archetype and tension age",
         "Show who wants what, and how old the grudge is. The age is what makes it read as "
         "authored rather than generated.",
         "Every listed contract shows the tick its tension was incurred.", 3, ["SS6.6"]),
    task("Accept and abandon a contract",
         "Acceptance is an event that propagates. Abandoning has a cost.",
         "Accepting a contract is visible to other entities through the belief graph.", 2, ["SS4.2"]),
    task("NPC entities rendered in the world",
         "Simulated people need bodies where the player is. Instanced characters placed from "
         "sim state, at the region the sim says they are in.",
         "An NPC the sim moves is seen to move, without a teleport.", 4, ["SS6.7"]),
    task("Approach and conversation entry",
         "Walk or fly to an NPC and open a conversation. No dialogue content yet.",
         "Conversation opens against the correct simulated entity, identified by id.", 3),
    task("Disclosure interaction: the four incentives",
         "Money, favour redemption, threat, and traded information, per SS6.3.",
         "Each incentive produces a different disclosure probability, visibly.", 4, ["SS6.3"]),
    task("Search volume rendered as a region, not a pin",
         "SS6.3 is explicit: no quest markers. Draw the volume as a shaded region on the map "
         "and in the world.",
         "The volume visibly widens when a source contradicts an earlier one.", 4, ["SS6.3"]),
    task("Inquiry events propagate and the target reacts",
         "The closing edge of the core loop. Asking is itself an event.",
         "Asking enough people causes the target to relocate, traceably.", 3, ["SS4"]),
    task("Stale intelligence and the cost of delay",
         "A disclosure ages. Its confidence decays, and acting on old information fails.",
         "Waiting ten in-game days after a disclosure makes the location wrong.", 2, ["SS6.1"]),
    task("Physical resolution: locating the target on the surface",
         "Fly to the region, find the target's actual position, and approach.",
         "The target is physically present at the location the sim holds, not spawned on arrival.",
         4, ["SS4.2"]),
    task("Capture alive versus kill",
         "Alive is worth more and requires approach and preparation. Dead is fast and loud.",
         "Killing generates worse events than capturing, measurably, in the belief graph.",
         3, ["SS4.2"]),
    task("Delivery choice and betrayal",
         "The posting corp is not the only buyer. A rival may pay more.",
         "Delivering to the rival is a betrayal event that propagates and changes disposition.",
         3, ["SS4.2"]),
    task("Consequence surfacing after the fact",
         "Show the player what their choice caused, days later, without telling them at the time.",
         "A betrayal produces a visible consequence at least one session later.", 3, ["SS2"]),
    task("Witness system and elimination",
         "Who saw what, and what happens if they do not survive to tell it.",
         "Removing the only witness measurably slows propagation of the act.", 3, ["SS6.1"]),
    task("Map view with belief overlay",
         "Show what the player knows, not what is true. Confidence and provenance visible.",
         "The map shows a contradicted location as two claims, not an average.", 4, ["SS6.1"]),
    task("Journal of leads and sources",
         "A record of who said what, when, and how sure they were.",
         "A player can reconstruct how they found a target from the journal alone.", 3, ["SS13.2"]),
    task("Scripted agent parity test",
         "The headless scripted agent and the player-facing loop must exercise the same code.",
         "A test drives the full loop headlessly and asserts the same events as a play session.",
         3, ["SS6.3", "SS11"]),
    task("Bounty loop balance pass",
         "Tune disclosure costs, decay rates and flight thresholds against the SS12 bands.",
         "Favour redemption 40-70%, false beliefs 10-25%, propagation depth 3-6 hops.",
         4, ["SS12"]),
    task("M5 evidence: a bounty, start to finish",
         "Record a full contract from board to delivery, with the journal visible.",
         "Recording plus journal export uploaded as milestone evidence.", 2, ["SS13.2"]),
]

# ---------------------------------------------------------------- M6
M6 = [
    task("Narration service skeleton in Python",
         "Design SS10's narration/ tree. A process that accepts structured state and returns "
         "text or an enum, batched and off the critical path.",
         "The sim runs identically with the service absent.", 3, ["SS6.4", "SS10"]),
    task("llama.cpp integration with a quantised local model",
         "3-8B at Q4 per SS6.4, with an explicit VRAM budget measured against the renderer.",
         "Inference runs alongside a 60 fps render without dropping frames.", 4, ["SS6.4"]),
    task("GBNF grammars for constrained action selection",
         "The model selects an enum variant, never free text that touches state.",
         "Every model output parses into a typed variant or is rejected; zero string parsing.",
         4, ["SS6.4"]),
    task("Renderers: news article from market state",
         "State to prose. The article is a lossy, biased rendering of true state.",
         "Articles lag the price move that caused them.", 3, ["SS6.5"]),
    task("Renderers: dialogue line from disposition and belief",
         "What an NPC says derives from what it believes and how it feels, both computed.",
         "Two NPCs with contradictory beliefs say contradictory things.", 4, ["SS6.4"]),
    task("Renderers: corporate filings and obligation notices",
         "Bureaucratic menace as text. The scariest thing in the setting is a compliance division.",
         "A filing references a real obligation with real numbers from the ledger.", 3, ["SS3"]),
    task("Authored fallback lines on timeout",
         "300 ms budget per SS6.4, with a fallback that is never obviously a fallback.",
         "Forcing every request to time out still produces a playable conversation.", 3, ["SS6.4"]),
    task("Batching and scheduling off the render thread",
         "Slow decisions only: faction moves on minutes, board text at refresh, dialogue at open.",
         "No inference call is made from the render thread, ever, asserted in code.", 3, ["SS6.4"]),
    task("Tier 5 stub-equivalence test",
         "A full sim run with narration stubbed must produce byte-identical world state.",
         "The test is in CI and fails if any narration path writes to authoritative state.",
         3, ["SS11", "SS6.4"]),
    task("Prompt and grammar versioning",
         "Prompts are code. Version them, and record which version produced which text.",
         "Any generated article can be traced to the prompt and model version that made it.",
         2, ["SS8.5"]),
    task("Narration cost and latency dashboard",
         "Measure tokens, latency and fallback rate per surface.",
         "Fallback rate is visible and under 5% in normal play.", 2, ["SS12"]),
    task("Cloud fallback decision and ADR",
         "SS15.6: local-only, or optional cloud for players without VRAM.",
         "An ADR recording the decision and its consequences for latency and privacy.",
         2, ["SS15.6", "SS8.5"]),
    task("M6 evidence: stubbed versus live equivalence",
         "Run both, diff the state hashes, capture the result.",
         "Diff output uploaded as milestone evidence.", 1, ["SS11"]),
]

# ---------------------------------------------------------------- M7
M7 = [
    task("Market instrument design and ADR",
         "SS15.5: order book, continuous double auction, or corp shares only. This determines "
         "the anti-bot surface.",
         "An ADR with the decision and the exploit surface it accepts.", 3, ["SS15.5", "SS8.5"]),
    task("Commodity supply and demand model",
         "Production, consumption and stock per region, moved by lanes.",
         "A blocked lane produces a shortage downstream within a legible number of ticks.",
         4, ["SS6.5"]),
    task("Price formation from supply and demand",
         "simulation event to supply/demand to price. Never the inverse.",
         "No price moves without a simulation event that caused it, asserted in a test.",
         3, ["SS6.5"]),
    task("Corporate balance sheets and share instruments",
         "Assets, liabilities, and shares outstanding that stay constant per instrument.",
         "Total shares outstanding per instrument is invariant over 1,000,000 ticks.",
         4, ["SS6.5", "SS12"]),
    task("Faucets and sinks, explicitly logged",
         "Money supply changes only through defined faucets and sinks, and they are logged.",
         "Every change to the money supply names its faucet or sink in the event log.",
         3, ["SS6.5"]),
    task("Bankruptcy and asset transfer to creditors",
         "Assets transfer; they never delete. The state space is a cycle, not a line.",
         "A bankrupt corp's assets sum to the same total after the transfer as before.",
         3, ["SS6.5"]),
    task("Mean-reversion pressure at scale",
         "Overhead rises with size; rivals coalesce against a leader.",
         "Gini over lane holdings oscillates rather than trending over 1,000,000 ticks.",
         3, ["SS6.5", "SS12"]),
    task("News feed UI with source bias",
         "Some outlets are captured. Corporate releases spin.",
         "Two outlets report the same event differently, and both are wrong in different ways.",
         4, ["SS6.5"]),
    task("Article lag behind price movement",
         "Players who watched the convoy die traded before the news broke.",
         "Articles are published a measurable number of ticks after the causing event.",
         2, ["SS6.5"]),
    task("Player trading interface",
         "Positions, orders, and a portfolio, in the instrument the ADR chose.",
         "A player can take a position on a corp and realise a gain from a simulated event.",
         4, ["SS6.5"]),
    task("Anti-bot friction, designed not discovered",
         "Knowledge that only exists inside physical conversations; positions requiring presence.",
         "A scripted client with full market data cannot outperform a player who travels.",
         4, ["SS6.5"]),
    task("Tier 3 fuzz over the economy for 1,000,000 ticks",
         "Adversarial scripted agent, every invariant asserted continuously, nightly in CI.",
         "The nightly run is green for seven consecutive nights.", 4, ["SS11", "SS12"]),
    task("Economy metrics dashboard",
         "Per-region tick cost, Gini, dominance, money supply, faucet and sink volumes.",
         "All SS12 economy metrics are visible on one page and alert outside their bands.",
         3, ["SS12"]),
    task("Cornering and manipulation testing",
         "Try to corner a market deliberately and see whether the invariants hold.",
         "A deliberate corner attempt is either impossible or self-correcting within N ticks.",
         3, ["SS6.5", "SS14 R4"]),
    task("M7 evidence: trade ahead of the news",
         "Record watching a convoy die, taking a position, and the article arriving late.",
         "Recording uploaded as milestone evidence.", 2, ["SS6.5"]),
]
