// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_ManageAudio : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_audio"); }
	FString GetDescription() const override { return TEXT("Play/stop sounds, add audio components, configure mixes, attenuation, spatial audio, and author Sound Cues/MetaSounds."); }
	FString GetCategory() const override { return TEXT("utility"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("actorName"), TEXT("Target actor label or name in the current level."));
			Schema.String(TEXT("analysisType"), TEXT("Audio analysis type to enable (for example spectrum or loudness)."));
			Schema.String(TEXT("assetPath"), TEXT("Canonical /Game asset path."));
			Schema.String(TEXT("attachPointName"), TEXT("Socket or bone name to attach the sound to."));
			Schema.String(TEXT("attenuationPath"), TEXT("Canonical /Game SoundAttenuation asset path."));
			Schema.String(TEXT("attenuationShape"), TEXT("Attenuation shape (Sphere, Capsule, Box, Cone)."));
			Schema.Bool(TEXT("autoPlay"), TEXT("Whether the sound starts playing on spawn."));
			Schema.String(TEXT("componentName"), TEXT("Name of the component to create or address."));
			Schema.String(TEXT("concurrencyPath"), TEXT("Canonical /Game SoundConcurrency asset path."));
			Schema.String(TEXT("defaultValue"), TEXT("Default value for the input."));
			Schema.Number(TEXT("dopplerIntensity"), TEXT("Doppler effect intensity multiplier."));
			Schema.String(TEXT("effectType"), TEXT("Source effect preset class or short name."));
			Schema.Bool(TEXT("enable"), TEXT("Whether the feature is enabled."));
			Schema.String(TEXT("enableReverbSend"), TEXT("Whether the sound sends to reverb."));
			Schema.Bool(TEXT("enabled"), TEXT("Whether the feature is enabled."));
			Schema.Number(TEXT("fadeInTime"), TEXT("Fade-in duration in seconds."));
			Schema.Number(TEXT("fadeOutTime"), TEXT("Fade-out duration in seconds."));
			Schema.Number(TEXT("fadeTime"), TEXT("Fade duration in seconds."));
			Schema.String(TEXT("fadeType"), TEXT("Fade curve type (FadeTo, FadeIn, FadeOut)."));
			Schema.Number(TEXT("falloffDistance"), TEXT("Distance over which attenuation falls off, in centimetres."));
			Schema.String(TEXT("falloffMode"), TEXT("Attenuation falloff mode."));
			Schema.Number(TEXT("innerRadius"), TEXT("Inner radius of full volume, in centimetres."));
			Schema.String(TEXT("inputName"), TEXT("Graph input name."));
			Schema.String(TEXT("inputType"), TEXT("Graph input data type (Float, Int32, Bool, String, Trigger, Audio)."));
			Schema.FreeformObject(TEXT("location"), TEXT("World location as {x, y, z} (an [x, y, z] array is accepted)."));
			Schema.Bool(TEXT("looping"), TEXT("Whether playback loops."));
			Schema.Number(TEXT("lowPassFilterFrequency"), TEXT("Low-pass filter cutoff frequency in Hz."));
			Schema.String(TEXT("mixName"), TEXT("Sound Mix name."));
			Schema.String(TEXT("name"), TEXT("Name of the asset or mapping to create or remove."));
			Schema.String(TEXT("nodeClassName"), TEXT("Node class name; short names such as Sine resolve against the MetaSound registry (UE.Sine.Audio)."));
			Schema.String(TEXT("nodeType"), TEXT("Node type or class short name."));
			Schema.Number(TEXT("occlusionFilterScale"), TEXT("Low-pass filter scale applied while occluded (0-1)."));
			Schema.Number(TEXT("occlusionInterpolationTime"), TEXT("Seconds to interpolate occlusion changes."));
			Schema.Number(TEXT("occlusionVolumeScale"), TEXT("Volume scale applied while occluded (0-1)."));
			Schema.String(TEXT("outputName"), TEXT("Graph output name."));
			Schema.String(TEXT("outputType"), TEXT("Graph output data type."));
			Schema.String(TEXT("parentClass"), TEXT("Parent class path or short name."));
			Schema.String(TEXT("path"), TEXT("Canonical /Game folder for the created asset."));
			Schema.Number(TEXT("pitch"), TEXT("Pitch multiplier."));
			Schema.FreeformObject(TEXT("properties"), TEXT("Key-value property map applied by reflection."));
			Schema.String(TEXT("reverbDistanceMax"), TEXT("Distance at which the reverb wet level reaches its maximum."));
			Schema.String(TEXT("reverbDistanceMin"), TEXT("Distance at which the reverb send starts."));
			Schema.String(TEXT("reverbEffect"), TEXT("Canonical /Game ReverbEffect asset path."));
			Schema.String(TEXT("reverbWetLevelMax"), TEXT("Maximum reverb wet level (0-1)."));
			Schema.String(TEXT("reverbWetLevelMin"), TEXT("Minimum reverb wet level (0-1)."));
			Schema.FreeformObject(TEXT("rotation"), TEXT("World rotation as {pitch, yaw, roll}."));
			Schema.Bool(TEXT("save"), TEXT("Persist the created or modified asset to disk."));
			Schema.FreeformObject(TEXT("size"), TEXT("Reverb zone extent as {x, y, z}."));
			Schema.String(TEXT("soundClassName"), TEXT("Sound Class name."));
			Schema.String(TEXT("soundClassPath"), TEXT("Canonical /Game SoundClass asset path."));
			Schema.String(TEXT("soundName"), TEXT("Actor label/name or AudioComponent name of the playing sound."));
			Schema.String(TEXT("soundPath"), TEXT("Canonical /Game sound asset path (SoundWave, SoundCue or MetaSound)."));
			Schema.String(TEXT("sourceNode"), TEXT("Source node id or name."));
			Schema.String(TEXT("sourceNodeId"), TEXT("Source graph node id."));
			Schema.String(TEXT("sourceOutputName"), TEXT("Output pin name on the source node."));
			Schema.String(TEXT("sourcePin"), TEXT("Output pin name on the source node."));
			Schema.String(TEXT("spatialization"), TEXT("Spatialization method (Default, Binaural)."));
			Schema.String(TEXT("speakerPath"), TEXT("Canonical /Game DialogueVoice asset path of the speaker."));
			Schema.Number(TEXT("startTime"), TEXT("Playback start offset in seconds."));
			Schema.String(TEXT("targetInputName"), TEXT("Input pin name on the target node."));
			Schema.String(TEXT("targetNode"), TEXT("Target node id or name."));
			Schema.String(TEXT("targetNodeId"), TEXT("Target graph node id."));
			Schema.String(TEXT("targetPin"), TEXT("Input pin name on the target node."));
			Schema.Number(TEXT("targetVolume"), TEXT("Target volume multiplier (0-1)."));
			Schema.Number(TEXT("velocityScale"), TEXT("Velocity scale for Doppler calculations."));
			Schema.Number(TEXT("volume"), TEXT("Volume multiplier."));
			Schema.String(TEXT("volumeAdjuster"), TEXT("Volume multiplier applied by the mix modifier."));
			Schema.String(TEXT("wavePath"), TEXT("Canonical /Game SoundWave asset path."));
			Schema.Number(TEXT("windowSize"), TEXT("Analysis window size in samples."));
			Schema.StringEnum(TEXT("action"), { TEXT("add_cue_node"), TEXT("add_metasound_input"), TEXT("add_metasound_node"), TEXT("add_metasound_output"), TEXT("add_mix_modifier"), TEXT("add_source_effect"), TEXT("clear_sound_mix_class_override"), TEXT("configure_distance_attenuation"), TEXT("configure_mix_eq"), TEXT("configure_occlusion"), TEXT("configure_reverb_send"), TEXT("configure_spatialization"), TEXT("connect_cue_nodes"), TEXT("connect_metasound_nodes"), TEXT("create_ambient_sound"), TEXT("create_attenuation_settings"), TEXT("create_audio_component"), TEXT("create_dialogue_voice"), TEXT("create_dialogue_wave"), TEXT("create_metasound"), TEXT("create_reverb_effect"), TEXT("create_reverb_zone"), TEXT("create_sound_class"), TEXT("create_sound_cue"), TEXT("create_sound_mix"), TEXT("create_source_effect_chain"), TEXT("create_submix_effect"), TEXT("enable_audio_analysis"), TEXT("fade_sound"), TEXT("fade_sound_in"), TEXT("fade_sound_out"), TEXT("get_audio_info"), TEXT("play_sound_2d"), TEXT("play_sound_at_location"), TEXT("play_sound_attached"), TEXT("pop_sound_mix"), TEXT("prime_sound"), TEXT("push_sound_mix"), TEXT("set_audio_occlusion"), TEXT("set_base_sound_mix"), TEXT("set_class_parent"), TEXT("set_class_properties"), TEXT("set_cue_attenuation"), TEXT("set_cue_concurrency"), TEXT("set_dialogue_context"), TEXT("set_doppler_effect"), TEXT("set_metasound_default"), TEXT("set_sound_attenuation"), TEXT("set_sound_mix_class_override"), TEXT("spawn_sound_at_location") }, TEXT("Action to invoke on manage_audio."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedUtility_AudioCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_ManageAudio());

}
