// Cube-sphere quadtree terrain. Design §6.8.
//
// Six root faces, recursively subdivided against a screen-space error metric
// relative to camera altitude. Crack prevention by edge-index stitching, not
// skirts. Collision cooked only near the player, async, off the game thread.
//
// **Geometry is generated on worker threads.** ADR-0002 measured a 33x33 patch
// at 5–8 ms of game-thread time and concluded that was the ceiling on the whole
// implementation — the budget could buy smooth frames or a filled horizon, not
// both. Moving generation to the task graph removes the choice: the game thread
// now only uploads finished vertex buffers, and the machine's other cores do the
// sampling. That is also what makes a real-scale planet and a seven-octave
// ridged multifractal affordable at all.
//
// Nanite is deliberately absent: its clusters are built offline, so a
// runtime-generated streamed quadtree cannot use it (design §6.8, amended v1.1).

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "LedgerTerrainMath.h"
#include "ProceduralMeshComponent.h"
#include <atomic>
#include "LedgerPlanet.generated.h"

class UProceduralMeshComponent;

/// A node of the quadtree. Plain data — the tree is walked, not dispatched to.
struct FLedgerQuadNode
{
	ELedgerCubeFace Face = ELedgerCubeFace::PositiveX;
	int32 Depth = 0;

	/// Position and extent within the face's `[0,1]^2` parameter space.
	double U = 0.0;
	double V = 0.0;
	double Extent = 1.0;

	/// Centre of the node on the reference sphere, in planet-local space. Mesh
	/// vertices are built relative to this so float precision stays local —
	/// which is what lets the same code run at 60 km or at 6,371 km without the
	/// vertices falling apart.
	FVector3d Centre = FVector3d::ZeroVector;

	/// Approximate world-space extent of the node in centimetres.
	double WorldSize = 0.0;

	TStaticArray<TUniquePtr<FLedgerQuadNode>, 4> Children;
	bool bHasChildren = false;

	/// Set each frame by the LOD pass. A node on the far side of the planet is
	/// neither drawn nor subdivided.
	bool bVisible = true;

	bool IsLeaf() const { return !bHasChildren; }
};

/// One patch of geometry being generated on a worker thread.
///
/// Every input is copied in at launch so the worker never touches the actor, the
/// quadtree, or anything else the game thread may be mutating. That is the whole
/// thread-safety argument, and it is why the inputs are values rather than
/// pointers.
struct FLedgerPatchJob
{
	// ---- inputs, immutable once launched --------------------------------
	uint64 Key = 0;
	int32 SectionIndex = INDEX_NONE;
	bool bWithCollision = false;

	ELedgerCubeFace Face = ELedgerCubeFace::PositiveX;
	double U = 0.0;
	double V = 0.0;
	double Extent = 1.0;
	FVector3d Centre = FVector3d::ZeroVector;

	FLedgerTerrainParams Params;
	int32 Side = 33;

	/// Edges that border a coarser neighbour and therefore need stitching.
	bool bStitchLeft = false;
	bool bStitchRight = false;
	bool bStitchBottom = false;
	bool bStitchTop = false;

	// ---- outputs --------------------------------------------------------
	TArray<FVector> Vertices;
	TArray<int32> Triangles;
	TArray<FVector> Normals;
	TArray<FVector2D> UVs;
	TArray<FColor> Colors;
	TArray<FProcMeshTangent> Tangents;

	/// The sea surface for this patch, as a second mesh section.
	///
	/// Water rides the terrain quadtree rather than having a quadtree of its
	/// own: it inherits the LOD, it is generated by the same job on the same
	/// thread, and its resolution can never disagree with the coastline it meets.
	/// A separate water tree would be a second streaming system to keep in step
	/// with the first, and the seam between them would be exactly at the
	/// shoreline, where it is most visible.
	TArray<FVector> WaterVertices;
	TArray<int32> WaterTriangles;
	TArray<FVector> WaterNormals;
	TArray<FVector2D> WaterUVs;
	TArray<FColor> WaterColors;
	TArray<FProcMeshTangent> WaterTangents;
	bool bHasWater = false;

	double GenerationMs = 0.0;

	/// Written last by the worker, read by the game thread. Release/acquire, so
	/// the buffers above are guaranteed visible once this reads true.
	std::atomic<bool> bComplete{false};

	/// Set by the game thread when the patch is no longer wanted — the LOD moved
	/// on while it was in flight. The result is dropped rather than uploaded.
	std::atomic<bool> bAbandoned{false};
};

using FLedgerPatchJobRef = TSharedPtr<FLedgerPatchJob, ESPMode::ThreadSafe>;

/// What the terrain is doing, for the §15.1 build/buy decision.
USTRUCT()
struct FLedgerTerrainStats
{
	GENERATED_BODY()

	UPROPERTY()
	int32 VisibleNodes = 0;

	UPROPERTY()
	int32 NodesWithCollision = 0;

	UPROPERTY()
	int32 JobsInFlight = 0;

	UPROPERTY()
	int32 PendingBuilds = 0;

	UPROPERTY()
	int64 TotalBuilds = 0;

	UPROPERTY()
	int32 DeepestVisibleDepth = 0;

	/// Game-thread milliseconds spent uploading finished patches last frame.
	/// This is now the *only* terrain cost on the game thread.
	UPROPERTY()
	double LastFrameUploadMs = 0.0;

	UPROPERTY()
	double WorstFrameUploadMs = 0.0;

	/// Worker-thread milliseconds for a single patch. Off the critical path, so
	/// this can be large without costing a frame — it only bounds throughput.
	UPROPERTY()
	double LastPatchGenerationMs = 0.0;

	UPROPERTY()
	double WorstFrameCollisionMs = 0.0;

	UPROPERTY()
	int32 WaterSections = 0;
};

UCLASS()
class LEDGERCLIENT_API ALedgerPlanet : public AActor
{
	GENERATED_BODY()

public:
	ALedgerPlanet();

	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type Reason) override;
	virtual void Tick(float DeltaSeconds) override;

	/// Reference sphere radius in centimetres. Earth: 6,371 km.
	///
	/// LWC carries this without complaint — 6.37e8 cm is well inside a double's
	/// envelope (§6.8) — and the mesh does not care either, because vertices are
	/// built relative to each node's own centre and never leave float range.
	UPROPERTY(EditAnywhere, Category = "Ledger|Planet")
	double Radius = 637100000.0;

	/// Peak elevation above the reference sphere. Earth's is about 9 km, which
	/// is 0.14% of its radius — invisible from orbit, and correctly so. What
	/// makes a planet read from space is the coastline, not the relief.
	UPROPERTY(EditAnywhere, Category = "Ledger|Planet")
	double MaxElevation = 900000.0;

	/// Where the waterline sits in the continent noise, in [-1, 1]. Higher means
	/// less land; Earth is about 71% ocean.
	/// 0.14 puts roughly two thirds of the surface under water, which is close
	/// to Earth and, more to the point, gives coastlines something to be a coast
	/// *of*. At 0.06 the planet was one supercontinent with ponds.
	UPROPERTY(EditAnywhere, Category = "Ledger|Planet")
	double SeaLevel = 0.14;

	UPROPERTY(EditAnywhere, Category = "Ledger|Planet")
	int32 Seed = 20260908;

	/// Vertices along one edge of a node's grid. Must be odd so edge stitching
	/// has a midpoint to collapse.
	/// 65 rather than 33: a patch with twice the vertices per side covers four
	/// times the ground at the same screen-space error, so the same triangle
	/// count arrives in a quarter of the draw calls. At 33 the visible set hit
	/// eighteen thousand components and the pool starved into a checkerboard of
	/// holes.
	UPROPERTY(EditAnywhere, Category = "Ledger|Planet")
	int32 GridResolution = 65;

	/// 15 levels of 64-quad patches over a 6,371 km planet: ~4.8 m quads.
	UPROPERTY(EditAnywhere, Category = "Ledger|Planet")
	int32 MaxDepth = 15;

	/// Subdivide when a node's projected error exceeds this many pixels.
	/// Paired with the patch resolution above: together they set how many
	/// components the visible set needs. 150 px with 65-vertex patches lands
	/// near a thousand, which the pool can actually serve.
	UPROPERTY(EditAnywhere, Category = "Ledger|LOD")
	double ErrorThresholdPixels = 150.0;

	/// Patches allowed in flight at once. Bounded so a fast turn cannot queue
	/// thousands of jobs whose results are stale before they land.
	UPROPERTY(EditAnywhere, Category = "Ledger|LOD")
	int32 MaxJobsInFlight = 64;

	/// Milliseconds per frame the game thread may spend uploading finished
	/// patches. Generation is no longer on this budget — only the upload is.
	UPROPERTY(EditAnywhere, Category = "Ledger|LOD")
	double UploadBudgetMs = 6.0;

	/// Cook collision within this distance of the camera.
	UPROPERTY(EditAnywhere, Category = "Ledger|Collision")
	double CollisionRadius = 300000.0;

	/// Cook ahead along the velocity vector by this many seconds of travel.
	/// Predictive, never on demand — §6.8's one non-negotiable.
	UPROPERTY(EditAnywhere, Category = "Ledger|Collision")
	double CollisionLeadSeconds = 2.5;

	const FLedgerTerrainStats& GetStats() const { return Stats; }

	/// Height of the surface above the reference sphere at a direction.
	double SurfaceRadiusAt(const FVector3d& UnitDirection) const;

	FLedgerTerrainParams TerrainParams() const;

private:
	UPROPERTY()
	TObjectPtr<USceneComponent> Root;

	UPROPERTY()
	TArray<TObjectPtr<UProceduralMeshComponent>> MeshPool;

	UPROPERTY()
	TObjectPtr<UMaterialInterface> SurfaceMaterial;

	UPROPERTY()
	TObjectPtr<UMaterialInterface> WaterMaterial;

	TArray<TUniquePtr<FLedgerQuadNode>> Roots;

	/// Leaf key -> index into `MeshPool`, for patches whose geometry is live.
	TMap<uint64, int32> ActiveSections;
	/// Leaf key -> job, for patches currently being generated.
	TMap<uint64, FLedgerPatchJobRef> InFlight;
	TArray<int32> FreeSections;

	FLedgerTerrainStats Stats;
	TArray<IConsoleObject*> ConsoleCommands;

	FVector3d LastCameraLocal = FVector3d::ZeroVector;
	FVector3d CameraVelocityLocal = FVector3d::ZeroVector;
	double NextTraceAt = 0.0;

	void BuildRoots();
	void UpdateTree(FLedgerQuadNode& Node, const FVector3d& CameraLocal, double ViewportWidth, double FovRadians);
	void CollectLeaves(const FLedgerQuadNode& Node, TArray<const FLedgerQuadNode*>& Out) const;
	void Split(FLedgerQuadNode& Node);
	void Collapse(FLedgerQuadNode& Node);
	bool IsBeyondHorizon(const FLedgerQuadNode& Node, const FVector3d& CameraLocal) const;

	/// Depth of the leaf containing a direction. Used for edge stitching, and it
	/// crosses cube faces for free because it starts from the direction rather
	/// than from a face-local coordinate.
	int32 LeafDepthAt(const FVector3d& UnitDirection) const;

	/// Launches generation on a worker thread. Returns false if the pool or the
	/// in-flight cap is exhausted.
	bool LaunchPatch(const FLedgerQuadNode& Node, bool bWithCollision);

	/// Uploads whatever finished since last frame, within the budget.
	void HarvestCompletedPatches();

	void ReleaseSection(uint64 Key);
	void AbandonJob(uint64 Key);

	FVector3d UnitSphereAt(const FLedgerQuadNode& Node, double LocalU, double LocalV) const;

	void LogStats() const;
};

/// Generates a patch's geometry. Free function, no engine state, safe to call
/// from any thread — which is the point.
LEDGERCLIENT_API void LedgerGeneratePatch(FLedgerPatchJob& Job);
