// Stones, generated by rule. T434, ADR-0005.
//
// The scatter had been placing the settlement's tree mesh -- an eighteen metre
// cone -- scaled down to the size of a cobble, which from above reads as a
// field of small black shards. The code that did it said so in a comment and
// asked for this.
//
// A rock is the one natural object a rule generates convincingly: it has no
// structure to get wrong, no growth pattern, no symmetry that has to be right.
// A sphere pushed around by noise and shaded flat is a rock, and a sphere
// pushed around by different noise is a different rock.

#pragma once

#include "CoreMinimal.h"

struct FLedgerMeshBuilder;

namespace LedgerRock
{
	/// How many distinct stones are baked. Three is enough that a scree slope
	/// does not read as one shape repeated, and few enough that the whole
	/// scatter is three draws.
	inline constexpr int32 Variants = 3;

	/// Appends one stone, roughly a metre across, centred on the origin with
	/// its base at z=0.
	///
	/// `Seed` picks the shape. `Roundness` in [0,1] runs from an angular
	/// fragment to a water-worn cobble, which is the one axis of variety that
	/// reads at a distance -- scree is angular because it broke off yesterday
	/// and a river stone is round because it did not.
	LEDGERCLIENT_API void Describe(
		FLedgerMeshBuilder& Builder, uint32 Seed, double Roundness);
}
