# -*- coding: utf-8 -*-
"""Regenerates every generated asset in the project, from its definition.

    python tools/generate_assets.py              everything
    python tools/generate_assets.py --only level
    python tools/generate_assets.py --list       the steps, and what each makes

**Why one command.** ADR-0005 says every asset in this game is generated by
rule; ADR-0006 says the rule runs once, offline, producing a real asset. Both
are only true if running the rules again is a command rather than an afternoon.
Three generators already existed and each had its own invocation, which is how a
project ends up with assets nobody can rebuild because nobody remembers how.

**What this does not do.** It does not decide whether regeneration is needed.
Every step runs every time, because the alternative is a dependency graph that
is wrong in one direction or the other, and being wrong towards "skipped a step"
means shipping a stale asset. The whole thing is minutes.

Each step's output records the generator that produced it, so an asset can
answer where it came from without this file being consulted.
"""

import argparse
import io
import json
import os
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT = os.path.join(ROOT, "client", "Ledger.uproject")
BUILD = os.path.join(ROOT, "build")

ENGINE = os.environ.get("UE_ROOT", r"C:\Program Files\Epic Games\UE_5.8")
EDITOR = os.path.join(ENGINE, "Engine", "Binaries", "Win64", "UnrealEditor.exe")
EDITOR_CMD = os.path.join(ENGINE, "Engine", "Binaries", "Win64", "UnrealEditor-Cmd.exe")


def python_step(script):
    return [EDITOR_CMD, PROJECT, "-run=pythonscript",
            "-script=" + os.path.join(ROOT, script),
            "-unattended", "-nopause", "-nosourcecontrol"]


# Order matters exactly once: the material bake needs the surface textures to be
# imported, because the terrain material samples them and reads their tiling out
# of the manifest. Everything else is independent.
STEPS = [
    dict(
        name="level",
        makes="/Game/Maps/Ledger",
        why="The map the project opens on, and the home of every actor that is "
            "placed rather than generated.",
        command=lambda: python_step("tools/make_level.py"),
    ),
    dict(
        name="surfaces",
        makes="/Game/Surfaces/*",
        why="Photogrammetric scans imported with the compression and colour "
            "space that follow from each map's role.",
        command=lambda: [
            EDITOR_CMD, PROJECT, "-run=ImportAssets",
            "-importsettings=" + os.path.join(BUILD, "surface-import.json"),
            "-nosourcecontrol", "-unattended", "-nopause"],
        prepare=lambda: subprocess.call(
            [sys.executable, os.path.join(ROOT, "tools", "make_import_settings.py")]),
    ),
    dict(
        name="materials",
        makes="/Game/Materials/*",
        why="The C++ graph builders, run once and saved, so a packaged build "
            "has a look at all.",
        command=lambda: [
            EDITOR, PROJECT, "-game", "-windowed", "-ResX=800", "-ResY=450",
            "-bakematerials", "-livematerials"],
    ),
]


def verify_level():
    return os.path.isfile(os.path.join(
        ROOT, "client", "Content", "Maps", "Ledger.umap")), "the map exists"


def verify_surfaces():
    root = os.path.join(ROOT, "client", "Content", "Surfaces")
    count = sum(1 for _, _, names in os.walk(root) for n in names if n.endswith(".uasset"))
    return count > 0, "%d textures imported" % count


def verify_materials():
    report = os.path.join(ROOT, "out", "bake-materials.txt")
    if not os.path.isfile(report):
        return False, "no bake report"
    body = io.open(report, encoding="utf-8").read()
    return "VERDICT: PASS" in body, body.strip().splitlines()[-1]


VERIFY = {"level": verify_level, "surfaces": verify_surfaces, "materials": verify_materials}


def run(step):
    """Runs one step and judges it by what it produced.

    Not by its exit code. Both Unreal entry points here return non-zero on a
    successful run -- the import commandlet validates an unused global block and
    fails on it, and the editor's own shutdown does not reliably return zero
    even when RequestExit was called with no error. A generator that trusts
    those either fails on success or, worse, succeeds on failure. So each step
    says what it should have produced and is asked whether it did."""
    if step.get("prepare"):
        step["prepare"]()

    started = time.time()
    subprocess.call(step["command"](), stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL)
    elapsed = time.time() - started

    ok, detail = VERIFY[step["name"]]()
    print("  %-11s %-24s %5.0f s  %s -- %s"
          % (step["name"], step["makes"], elapsed, "ok" if ok else "FAILED", detail))
    return ok


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--only", help="run one step by name")
    parser.add_argument("--list", action="store_true", help="say what the steps are")
    arguments = parser.parse_args()

    if arguments.list:
        for step in STEPS:
            print("  %-11s -> %s" % (step["name"], step["makes"]))
            print("              %s" % step["why"])
        return 0

    if not os.path.isfile(EDITOR_CMD):
        sys.stderr.write("no Unreal at %s. Set UE_ROOT.\n" % ENGINE)
        return 1

    chosen = [s for s in STEPS if arguments.only in (None, s["name"])]
    if not chosen:
        sys.stderr.write("no step called %r. Known: %s\n"
                         % (arguments.only, ", ".join(s["name"] for s in STEPS)))
        return 1

    os.makedirs(BUILD, exist_ok=True)
    print("regenerating %d step%s" % (len(chosen), "" if len(chosen) == 1 else "s"))

    failures = [s["name"] for s in chosen if not run(s)]

    # A record of what the project's generated assets are and what makes them.
    # The assets carry their own provenance in Unreal metadata; this is the
    # index, for the question "what is generated at all".
    with io.open(os.path.join(BUILD, "generated-assets.json"), "w",
                 encoding="utf-8", newline="\n") as handle:
        json.dump({
            "note": "Written by tools/generate_assets.py. Every asset listed is "
                    "derived and is not in version control; each carries a "
                    "Ledger.Generator tag naming what produced it.",
            "steps": [{"name": s["name"], "makes": s["makes"], "why": s["why"]}
                      for s in STEPS],
        }, handle, indent=2)
        handle.write("\n")

    if failures:
        sys.stderr.write("\nfailed: %s\n" % ", ".join(failures))
        return 1
    print("\nevery generated asset rebuilt from its definition")
    return 0


if __name__ == "__main__":
    sys.exit(main())
