# -*- coding: utf-8 -*-
"""Prints the shell line that lets the MCP client authenticate to the editor.

    python tools/mcp_token.py            the export line for this shell
    python tools/mcp_token.py --check    is the endpoint up and does the token work

**Why the token is not just written into .mcp.json.** That file is committed,
the repository is public, and this token authorises spawning actors, running
Python and issuing console commands inside the editor. So .mcp.json refers to
`${UNREAL_MCP_TOKEN}` and the value stays in `client/Saved/`, which is ignored.

The token is generated by the plugin on first run and does not change.
"""

import argparse
import io
import json
import os
import sys
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOKEN_FILE = os.path.join(ROOT, "client", "Saved", "MCP", "capability-token")
ENDPOINT = "http://127.0.0.1:3000/mcp"


def read_token():
    if not os.path.isfile(TOKEN_FILE):
        sys.stderr.write(
            "no capability token at %s\n"
            "The plugin writes it the first time the editor runs with the native\n"
            "MCP server enabled. Open the project in the editor once.\n" % TOKEN_FILE)
        return None
    with io.open(TOKEN_FILE, encoding="utf-8") as handle:
        return handle.read().strip()


def check(token):
    """Initialises a session, which proves the endpoint, the token and the
    editor are all actually working -- rather than that a port is open."""
    body = json.dumps({
        "jsonrpc": "2.0", "id": 1, "method": "initialize",
        "params": {"protocolVersion": "2025-06-18", "capabilities": {},
                   "clientInfo": {"name": "mcp_token.py", "version": "1"}},
    }).encode("utf-8")

    request = urllib.request.Request(ENDPOINT, data=body, method="POST")
    request.add_header("Content-Type", "application/json")
    request.add_header("Accept", "application/json, text/event-stream")
    request.add_header("X-MCP-Capability-Token", token)

    try:
        with urllib.request.urlopen(request, timeout=15) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as problem:
        print("  endpoint  %s  UNREACHABLE (%s)" % (ENDPOINT, problem))
        print("  The editor must be open. The native MCP server only runs in-editor.")
        return 1
    except Exception as problem:
        print("  endpoint  %s  FAILED (%s)" % (ENDPOINT, problem))
        return 1

    if "error" in payload:
        print("  endpoint  %s  reachable, token REJECTED: %s"
              % (ENDPOINT, payload["error"].get("message")))
        return 1

    server = payload.get("result", {}).get("serverInfo", {})
    print("  endpoint  %s" % ENDPOINT)
    print("  server    %s %s" % (server.get("name"), server.get("version")))
    print("  token     accepted")
    print("\nVERDICT: PASS")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the endpoint answers and the token is accepted")
    arguments = parser.parse_args()

    token = read_token()
    if token is None:
        return 1

    if arguments.check:
        return check(token)

    # Printed for the user's shell, not echoed anywhere that gets committed.
    if os.name == "nt":
        print('setx UNREAL_MCP_TOKEN "%s"' % token)
        print('$env:UNREAL_MCP_TOKEN = "%s"   # this PowerShell session only' % token)
    else:
        print('export UNREAL_MCP_TOKEN="%s"' % token)
    return 0


if __name__ == "__main__":
    sys.exit(main())
