# -*- coding: utf-8 -*-
"""Every asset in the project answers where it came from.

    UnrealEditor-Cmd <project> -run=pythonscript -script=tools/verify_assets.py

ADR-0005 and ADR-0006: everything here is generated by rule, offline, into a
real asset. That is only checkable if each asset says which rule -- so this
walks the whole content tree and reports anything that does not.

**Why this matters more than it sounds.** An asset with no generator behind it
is an asset nobody can rebuild. It survives because deleting it feels risky, and
two years later the content tree is half things somebody made by hand once and
cannot reproduce. The surfaces manifest exists for the same reason and caught
the same class of problem: not "is this free" but "free to do *what*".

It also checks that package paths are derived rather than typed, by requiring
each asset to sit under the root its kind belongs to.
"""
import os

import unreal

# Where each kind of generated asset belongs. A path is derived from the
# definition that produced it; anything outside these was put somewhere by hand.
ROOTS = {
    "/Game/Materials": "baked material",
    "/Game/Meshes": "baked static mesh",
    "/Game/Surfaces": "imported surface texture",
    "/Game/Maps": "level",
}

registry = unreal.AssetRegistryHelpers.get_asset_registry()
registry.scan_paths_synchronous(["/Game"], force_rescan=True)

missing = []
misplaced = []
counts = {}
checked = 0

for data in registry.get_assets_by_path("/Game", recursive=True):
    package = str(data.package_name)
    checked += 1

    home = next((root for root in ROOTS if package.startswith(root + "/")), None)
    if home is None:
        misplaced.append(package)
        continue
    counts[home] = counts.get(home, 0) + 1

    generator = unreal.EditorAssetLibrary.get_metadata_tag(
        data.get_asset(), "Ledger.Generator")
    if not generator:
        missing.append(package)

# The level, explicitly.
#
# get_assets_by_path does not return World assets, so the first version of this
# reported "/Game/Maps 0" and passed -- having never looked at the one asset the
# whole project opens on. A validator that quietly checks nothing is worse than
# no validator, because it is believed.
LEVEL = "/Game/Maps/Ledger"
LEVEL_FILE = os.path.normpath(os.path.join(
    unreal.Paths.project_dir(), "Content", "Maps", "Ledger.umap"))

if not os.path.isfile(LEVEL_FILE):
    missing.append(LEVEL + " (no .umap on disk)")
else:
    checked += 1
    counts["/Game/Maps"] = counts.get("/Game/Maps", 0) + 1
    # A level's object path is package plus object name, and does_asset_exist
    # on the package path alone answers no. Asked the way the engine expects.
    # The level is the one asset whose generator cannot be recorded in the
    # asset. Unreal's map save drops package metadata set before it, and
    # save_asset on a map does not persist metadata set after it -- both were
    # tried. So its provenance is kept beside it, in the report the generator
    # writes, and checked there. Stated rather than waved through: an exception
    # nobody wrote down is how a rule stops meaning anything.
    record = os.path.normpath(os.path.join(
        unreal.Paths.project_dir(), "..", "build", "make-level.txt"))
    recorded = (os.path.isfile(record)
                and "Generator: tools/make_level.py" in open(record).read())
    if not recorded:
        missing.append(LEVEL + " (no generator recorded in build/make-level.txt)")

lines = ["Asset provenance, across the whole content tree.", ""]
for root in sorted(ROOTS):
    lines.append("  %-18s %4d  %s" % (root, counts.get(root, 0), ROOTS[root]))
lines.append("")
lines.append("  %d assets checked" % checked)

if misplaced:
    lines.append("")
    lines.append("  Outside every known root, so not produced by any generator:")
    for package in misplaced[:20]:
        lines.append("    %s" % package)

if missing:
    lines.append("")
    lines.append("  No Ledger.Generator tag, so nothing records how to rebuild them:")
    for package in missing[:20]:
        lines.append("    %s" % package)
    if len(missing) > 20:
        lines.append("    ... and %d more" % (len(missing) - 20))

lines.append("")
lines.append("VERDICT: %s" % (
    "PASS" if checked and not missing and not misplaced
    else "FAIL (%d untagged, %d misplaced, %d checked)"
         % (len(missing), len(misplaced), checked)))

out = os.path.normpath(os.path.join(unreal.Paths.project_dir(), "..", "out", "verify-assets.txt"))
with open(out, "w") as handle:
    handle.write("\n".join(lines) + "\n")
